version: "2"

services:
  web:
    restart: always
    image: portus
    command: puma -b tcp://0.0.0.0:3000 -w 3
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=portus.bys-control.com.ar
      - PORTUS_DB_HOST=db
      - VIRTUAL_HOST=portus.bys-control.com.ar
      - VIRTUAL_PORT=3000
    networks:
      - portus_net
    volumes:
      - /home/gbisheimer/src/docker/portus:/portus
    ports:
      - 3000:3000

  crono:
    restart: always
    image: portus
    entrypoint: bin/crono
    environment:
      - PORTUS_MACHINE_FQDN=portus.bys-control.com.ar
      - PORTUS_DB_HOST=db
    networks:
      - portus_net
    volumes:
      - /home/gbisheimer/src/docker/portus:/portus
      #- registry

  db:
    restart: always
    image: library/mariadb:10.0.23
    environment:
      - MYSQL_ROOT_PASSWORD=portus
      - MYSQL_USER=portus
      - MYSQL_DATABASE=portus
      - MYSQL_PASSWORD=portus
    networks:
      - portus_net

  registry:
    restart: always
    image: library/registry:2.3.1
    networks:
      - portus_net
    volumes:
      - /srv/docker/registry:/var/lib/registry
      - /home/gbisheimer/src/docker/portus/compose/registry/portus.crt:/etc/docker/registry/portus.crt:ro
      - /home/gbisheimer/src/docker/portus/compose/registry/config.yml:/etc/docker/registry/config.yml:ro
    environment:
      - VIRTUAL_HOST=registry.bys-control.com.ar
      - VIRTUAL_PORT=5000
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service

networks:
  portus_net:
    driver: bridge
